apiVersion: v1
kind: Service
metadata:
  name: zipkin-service
  labels:
    svc_appname: zipkin
    tier: ops
spec:
  selector:
    appname: zipkin
    tier: ops
  ports:
    - name: http
      port: 9411
      targetPort: 9411
  type: LoadBalancer
