{
 "title": "All Microservices",
 "description": "source, tier1, tier2, sink",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Source Method Calls",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "microservice_source_0_source_Send_methodCallsCOUNTER_timerMessageSource_count_total"
    }
   ]
  },
  {
   "title": "source method duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "microservice_source_0_source_Send_methodDurationTIMER_timerMessageSource_seconds_max"
    }
   ]
  },
  {
   "title": "tier2 method duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "microservice_tier2_0_sink2_Receive_methodDurationTIMER_sinkTier2StreamListener_seconds_max"
    }
   ]
  },
  {
   "title": "Tier1 Method Calls",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "microservice_tier1_0_sink1_Receive_methodCallsCOUNTER_sinkTier1StreamListener_count_total"
    }
   ]
  },
  {
   "title": "tier2 Method Calls",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "microservice_tier2_0_sink2_Receive_methodCallsCOUNTER_sinkTier2StreamListener_count_total"
    }
   ]
  },
  {
   "title": "tier1 method duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 4, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "microservice_tier1_0_sink1_Receive_methodDurationTIMER_sinkTier1StreamListener_seconds_max"
    }
   ]
  },
  {
   "title": "sink method duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 13, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "microservice_sink_0_sink_Receive_methodDurationTIMER_sinked_seconds_max"
    }
   ]
  },
  {
   "title": "sink Method Calls",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "microservice_sink_0_sink_Receive_methodCallsCOUNTER_sinked_count_total"
    }
   ]
  }
 ]
}