#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind": "Ingress"}),expects="1+"
---
metadata:
  name: #@ "{}-{}-{}".format(data.values.name, data.values.tier, "ingress")
spec:
  rules:
  #@overlay/match by="host"
  - host: ""
    http:
      paths:
      #@overlay/match by="path"
      - path: /greet
        backend:
          serviceName: #@ "{}-{}-{}".format(data.values.name, data.values.tier, "service")
    #@overlay/match by="host"
  - host: greet.mycluster.local
    http:
      paths:
        #@overlay/match by="path"
        - path: /greet
          backend:
            serviceName: #@ "{}-{}-{}".format(data.values.name, data.values.tier, "service")
