---
logging:
  level:
    #ROOT: DEBUG
    org.springframework.boot.context.config.ConfigFileApplicationListener: DEBUG
    #org.springframework.cloud.sleuth: DEBUG
    brave: DEBUG
  pattern:
    # MDC values have to be EXACTLY like in spring.sleuth.xxx-keys and whitelisted-mdc-keys
    # original from org.springframework.cloud.sleuth.autoconfig.TraceEnvironmentPostProcessor
  # level: "%5p [${spring.zipkin.service.name:${spring.application.name:-}},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]"
    level: "%5p [${spring.zipkin.service.name:${spring.application.name:-}},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}] [%X{ddd:-},%X{bp:-},%X{bpids:-}] [%X{op:-},%X{chunk:-},%X{i:-}]"

spring:
  #main:
  #  allow-bean-definition-overriding: true
  jackson.serialization.indent_output: true
  jmx:
    enabled: false
  sleuth:
    opentracing:
      enabled: true
    sampler:
      probability: 1.0
    annotation:
      enabled: true
    # keys that travel with inter-process calls (see BAGGAGEKEY.java)
    # these keys will be prefix by "baggage-" (if http) or "baggage_" (if messaging)
    baggage-keys:
    - bpids
    - ddd
    - bp
    local-keys: # keys that are only propagated within the app
    - op
    - chunk
    - i
    # keys that travel with inter-process calls (see MDCKEY.java)
    # these keys will not be prefixed
    propagation-keys: # keys that travel with inter-process calls unprefixed
    # - empty
    log:
      slf4j:
        whitelisted-mdc-keys: # (baggage|propagation)-keys that are copied to slf4j MDC for logging
        - bpids
        - ddd
        - bp
        - op
        - chunk
        - i
    rxjava:
      schedulers:
        ignoredthreads:
        - HystrixMetricPoller
        - ^RxComputation.*$
        - ^RxIoScheduler.*$
  zipkin:
    enabled: true
    base-url: ${ZIPKIN_URL:http://localhost:9411} # http://localhost:14268/api/traces #
    sender:
      type: web

resilience4j:
  circuitbreaker:
    configs: # create CircuitBreakerRegistries
      default: # configure the global CircuitBreakerRegistry defaults for creating CircuitBreakerConfig
        ring-buffer-size-in-closed-state: 5
        ring-buffer-size-in-half-open-state: 5
        wait-duration-in-open-state: 1000
        failure-rate-threshold: 33
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
      sourcesDefault: # Create a CircuitBreakerRegistry with a custom global configuration
        ring-buffer-size-in-closed-state: 3
        ring-buffer-size-in-half-open-state: 3
        wait-duration-in-open-state: 1000
        failure-rate-threshold: 20

# opentracing:
#   jaeger:
#     ## kebab-case properties of io.opentracing.contrib.java.spring.jaeger.starter.JaegerConfigurationProperties
#     enabled: true
#     enable-b3-propagation: true
#     # probabilistic-sampler:
#     #   sampling-rate: 0.5
#     # rate-limiting-sampler:
#     #   max-traces-per-second: 2.0
#     const-sampler:
#       decision: true
#     # udp-sender:
#     #   host: jaegerhost
#     #   port: 14268
#     http-sender:
#       url: http://localhost:14268/api/traces

app:
  info:
    application_id: ${vcap.application.application_id:local}
    instance_index: ${vcap.application.instance_index:0}
    instance_id: ${vcap.application.instance_id:local}
  sources:
    fixedDelay: 5000
  businessLogic:
    # tier name has to be given on command line or environment variable app.businessLogic.tier see scripts/run_microservice.sh
    tier: fixedfromapplicationproperties
    # @HystrixProperty(name = "execution.isolation.thread.timeoutInMilliseconds", value = "3000")
    # Tier1 has 4 businessLogic methods and Tier2 has 3 businessLogicMethods
    sleepMin: 265
    sleepMax: 1000

eureka:
 client:
   service-url:
     # cloudfoundry service instance name: vcap.services.HERE.credential.uri
     # has to match environments.config serviceInstanceName
     # has to match ci/variables.yml registryInstanceName
     defaultZone: ${vcap.services.testpoServiceRegistry.credentials.uri:http://localhost:8761}/eureka/

my:
  test:
    property: "from application.yml"

# management: --> bootstrap.yml

---
spring:
  profiles: source
  cloud:
    stream:
      bindings:
        minimal-SourceTo1: # has to match channels.SourceChannels.OUTPUT
          destination: minimal-SourceTo1
          contentType: application/json

resilience4j:
  circuitbreaker:
    instances: # creating CircuitBreaker instances
      source:
        base-config: sourcesDefault
        wait-duration-in-open-state: 3000
        # record-exceptions:
        # ignore-exceptions:

---
spring:
  profiles: tier1
  cloud:
    stream:
      bindings:
        minimal-SourceTo1: # has to match channels.Tier1Channels.INPUT
          group: tier1s
          destination: minimal-SourceTo1
          contentType: application/json
        minimal-1To2: # has to match channels.SourceChannels.OUTPUT
          destination: minimal-1To2
          contentType: application/json

resilience4j:
  circuitbreaker:
    instances: # creating CircuitBreaker instances
      tier1:
        base-config: default
        wait-duration-in-open-state: 3000
        # record-exceptions:
        # ignore-exceptions:

app:
  businessLogic:
    # Tier1 has 4 businessLogic methods and Tier2 has 3 businessLogicMethods
    sleepMin: 265
    sleepMax: 1000

---
spring:
  profiles: tier2
  cloud:
    stream:
      bindings:
        minimal-1To2: # has to match channels.Tier2Channels.INPUT
          group: tier2
          destination: minimal-1To2
          contentType: application/json
        minimal-2ToSink: # has to match channels.Tier2Channels.OUTPUT
          destination: minimal-2ToSink
          contentType: application/json

resilience4j:
  circuitbreaker:
    instances: # creating CircuitBreaker instances
      tier2:
        base-config: default
        wait-duration-in-open-state: 3000
        # record-exceptions:
        # ignore-exceptions:

app:
  businessLogic:
    # Tier1 has 4 businessLogic methods and Tier2 has 3 businessLogicMethods
    sleepMin: 265
    sleepMax: 1000

---
spring:
  profiles: sink
  cloud:
    stream:
      bindings:
        minimal-2ToSink: # has to match channels.SinkChannels.INPUT
          group: sink
          destination: minimal-2ToSink
          contentType: application/json

---
spring:
  profiles: local
  cloud:
    stream:
      default-binder: local_rabbit
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
#                username: <username>
#                password: <password>
#                virtual-host: /
logging:
  pattern:
    level: "%5p [${spring.zipkin.service.name:${spring.application.name:-}},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}] [%X{ddd:-},%X{bp:-},%X{bpids:-}] [%X{op:-},%X{chunk:-},%X{i:-}]\n"

---
spring:
  profiles: k8s
  cloud:
    stream:
      default-binder: local_rabbit
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: rabbitmq.rabbitmq-ns.svc.cluster.local
#                username: <username>
#                password: <password>
#                virtual-host: /
